name: Deploy docker image to AWS

on:
  workflow_run:
    workflows: ["Build & Push docker image to docker hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker logout
            sudo docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker rm $(sudo docker stop $(sudo docker ps -aqf ancestor=$(docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/react-app)))
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/react-app
            sudo docker image pull ${{ secrets.DOCKERHUB_USERNAME }}/react-app
            sudo docker run -d -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/react-app 