name: Deploy app to AWS EC2 Ubuntu server

on:
  workflow_run:
    workflows: ["Run Linting and Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: .ansible/main.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            ${{secrets.AWS}} address=localhost
          options: |
            -e GITHUB_REPO=${{github.repository}}
            -e NODE_ENV=${{vars.NODE_ENV}}
            -e APP_PORT=${{vars.APP_PORT}}
            -e APP_PATH=${{vars.APP_PATH}}

